name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      API_KEY: ${{ secrets.API_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      FROM: ${{ secrets.FROM }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew  # Gradle 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --stacktrace --info

      - name: Run Tests
        run: ./gradlew test  # 테스트 실행
